project:
  type: website
  render:
  - "01*.qmd"
  - "*.qmd"

website:
  title: "PEN America's Banned Books Index"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - auto: "*.qmd"

format:
  html:
    theme: cosmo
    toc: true
    df-print: paged
    code-overflow: wrap
